steps:
  - id: build dbt docker image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/dbt_test_pipeline
      - -f
      - Dockerfile
      - .
  -
images:
  - gcr.io/$PROJECT_ID/dbt_test_pipeline