steps:
  - id: build CI docker image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/dbt_ci:$SHORT_SHA
      - -f
      - Dockerfile-CI
      - .
  - id: run dag test
    name: gcr.io/cloud-builders/docker
    args:
      - run
      - gcr.io/$PROJECT_ID/dbt_ci:$SHORT_SHA

images:
  - gcr.io/$PROJECT_ID/dbt_ci:$SHORT_SHA