steps:
- id: clone repository
  name: gcr.io/cloud-builders/git
  args: 
    - clone 
    - https://github.com/dimasadiluhung/test_pipeline.git
  dir: /workspace
    
- id: fetch repository
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - git fetch
  dir: /workspace/test_pipeline

- id: checkout to feature branch
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - git checkout $BRANCH_NAME
  dir: /workspace/test_pipeline  

- id: pytest-dags
  name: gcr.io/$PROJECT_ID/dbt_ci
  entrypoint: bash
  args:
    - -c
    - pytest *; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret
  dir: /workspace/test_pipeline/dags
  
