steps:
- id: clone repository
  name: gcr.io/cloud-builders/git
  args: 
    - clone 
    - https://github.com/dimasadiluhung/test_pipeline.git
  dir: /workspace
    
- id: fetch repository
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - git fetch
  dir: /workspace/test_pipeline

- id: checkout to feature branch
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - git checkout $BRANCH_NAME
  dir: /workspace/test_pipeline
  
- id: check content 1
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - ls -al
  dir: /workspace

- id: check content 2
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: 
    - -c
    - ls -al
  dir: /workspace/test_pipeline


- id: pytest-dags
  name: gcr.io/$PROJECT_ID/dbt_ci
  entrypoint: bash
  args:
    - -c
    - for pyfile in *.py; do echo "pytest for "$pyfile; pytest $pyfile; done
  dir: /workspace/test_pipeline/dags
  
