steps:
  - id: build CI docker image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/dbt_ci
      - -f
      - Dockerfile-CI
      - .

images:
  - gcr.io/$PROJECT_ID/dbt_ci